services:
  mailrestserver:
    build:
      context: .
    volumes:
      - ./mnt:/mnt:ro
    restart: always
    user: "33:33"
    read_only: true
    networks:
      - main
    environment:
      - APPSETTINGS_IPADDRESS=mailrestserver

networks:
  main:
    name: main
    external: true
